export { default as Navbar } from './Navbar'
export { default as BookmarkManager } from './BookmarkManager'
export { default as FeatureHeading } from './FeatureHeading'
export { default as FeatureTabs } from './FeatureTabs'
export { default as DownloadHeading } from './DownloadHeading'
export { default as DownloadBoxes } from './DownloadBoxes'
export { default as HeadingFAQ } from './HeadingFAQ'
export { default as Footer } from './Footer'
